---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name dfguard-client-ca
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: security-ns
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: &key ca.crt
      remoteRef:
        key: *name
        property: *key
