---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dfguard
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/m00nwtchr/dfguard
              tag: 0.2.7@sha256:68109031670b6ebadc062a321c5f252c35a9c0be092dc47902b41bf4b989d861
            env:
              DFGUARD_UPSTREAM: dragonfly-cluster.database.svc.cluster.local:6379
              DFGUARD_SERVER_CERT: /tls/server/tls.crt
              DFGUARD_SERVER_KEY: /tls/server/tls.key
              DFGUARD_SERVER_CA: /tls/client/ca.crt
              DFGUARD_UPSTREAM_CERT: /tls/dragonfly/tls.crt
              DFGUARD_UPSTREAM_KEY: /tls/dragonfly/tls.key
              DFGUARD_UPSTREAM_CA: /tls/dragonfly/ca.crt
              DFGUARD_METRICS_LISTEN: '[::]:9464'
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /livez
                port: &metricsPort 9464
              readiness:
                enabled: true
                type: HTTP
                path: /readyz
                port: *metricsPort
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          redis:
            port: 6379
          metrics:
            port: *metricsPort

    persistence:
      acl:
        type: secret
        name: dragonfly-acls
        globalMounts:
          - path: /config
            readOnly: true

      tls:
        type: secret
        name: dfguard-server-cert
        globalMounts:
          - path: /tls/server
            readOnly: true
      client-ca:
        type: secret
        name: dfguard-client-ca
        globalMounts:
          - path: /tls/client
            readOnly: true

      dragonfly-cert:
        type: secret
        name: dfguard-client-cert
        globalMounts:
          - path: /tls/dragonfly
            readOnly: true

    rawResources:
      netpol:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        spec:
          spec:
            endpointSelector:
              matchLabels:
                app.kubernetes.io/name: *app
                app.kubernetes.io/instance: *app
            egress:
              - toEndpoints:
                  - matchLabels:
                      k8s:io.kubernetes.pod.namespace: database
                      app: dragonfly-cluster
                      app.kubernetes.io/name: dragonfly
                      app.kubernetes.io/part-of: dragonfly
                toPorts:
                  - ports:
                      - port: '6379'
                        protocol: TCP
