---
# yaml-language-server: $schema=https://schemas.tholinka.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app dragonfly-cluster
  labels:
    group: dragonfly
    app: *app
spec:
  selector:
    matchLabels:
      app: *app
  podTargetLabels: [app]
  podMetricsEndpoints:
    - port: admin
