---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.2.0
    digest: sha256:c7a0d919fa98da147ca06f39ebb745d1099b1caaf514a0edaa12980592426c71
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
