---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.3.0
    digest: sha256:3e3c6f9e106a86bae1951bcee55199fd444e9a45dab5fc5ac37422d6bc8b44c5
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
