---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.12.2
    digest: sha256:e8a7a2799e27046828b4fa9abebc2204a1ba355503bf1e8c8bfdb437b0ae834c
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
