[env]
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
JUST_UNSTABLE = "1"

[tools]
"aqua:evilmartians/lefthook" = "2.1.12"
"aqua:postfinance/topf" = "0.6.0"
"aqua:helmfile/vals" = "0.46.0"
"aqua:helmfile/helmfile" = "1.7.4"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:zizmorcore/zizmor" = "1.30.0"
"github:mitsuhiko/minijinja" = "2.24.0"

"npm:oxfmt" = "0.66.0"

"github:home-operations/flate" = "v0.6.5"

[hooks]
postinstall = "lefthook install"
