[env]
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
JUST_UNSTABLE = "1"

[tools]
"aqua:evilmartians/lefthook" = "2.1.10"
"aqua:budimanjojo/talhelper" = "3.1.13"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:zizmorcore/zizmor" = "1.27.0"

"npm:oxfmt" = "0.58.0"

"github:home-operations/flate" = "v0.4.10"

[hooks]
postinstall = "lefthook install"
