---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-collector
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.5
    digest: sha256:b63e74560a5d8402aea02012cda6a829525961286fd179fddef439fe0cd40490
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
