---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coredns
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.46.0
    digest: sha256:c0361031fa19ce0fbb894469286e0e9ac2555922f576213b0a7dbb8a0d2e1e35
  url: oci://ghcr.io/coredns/charts/coredns
