---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret upload-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    template:
      data:
        session-secret: '{{ .UA_SESSION_SECRET }}'
        webui_auth.json: '{{ .UA_WEBUI_AUTH }}'
        config.py: |-
          config = {
            "DEFAULT": {
                "verbose_notification": True,
                "tmdb_api": "{{ .TMDB_API }}",
                "img_host_1": "onlyimage",
                "img_host_2": "imgbox",
                "img_host_3": "imgbb",
                "imgbb_api": "{{ .UA_IMGBB_API }}",
                "onlyimage_api": "{{ .UA_ONLYIMAGE_API }}",
                "ping_unit3d": True,
                "get_bluray_info": True,
                "screens": "6",
                "use_sonarr": True,
                "sonarr_url": "http://sonarr.media.svc.cluster.local",
                "sonarr_api_key": "{{ .SONARR_API_KEY }}",
                "use_radarr": True,
                "radarr_url": "http://radarr.media.svc.cluster.local",
                "radarr_api_key": "{{ .RADARR_API_KEY }}",
                "prefer_max_16_torrent": False,
                "rehash_cooldown": "0",
                "inject_delay": "0",
                "show_upload_duration": True,
                "print_tracker_messages": True,
                "print_tracker_links": True,
                "search_requests": True,
                "check_predb": False,
                "cross_seeding": True,
                "cross_seed_check_everything": False,
                "default_torrent_client": "qbittorrent",
            },
            "TRACKERS": {
          {{ .UA_TRACKERS | indent 4 }}
            },
            "TORRENT_CLIENTS": {
                "qbittorrent": {
                    "torrent_client": "qbit",
                    "qui_proxy_url": "http://qui.media.svc.cluster.local/proxy/{{ .UA_QUI_API }}",
                    "enable_search": True,
                    "super_seed_trackers": "['']",
                    "use_tracker_as_tag": False,
                    "qbit_tag": "",
                    "qbit_cat": "uploader",
                    "qbit_cross_tag": "cross-seed",
                    "qbit_cross_cat": "cross-seed",
                    "content_layout": "Original",
                    "linking": "hardlink",
                    "allow_fallback": True,
                    "linked_folder": "['/media/downloads/qbittorrent/complete/uploader']",
                    "local_path": "['']",
                    "remote_path": "['']",
                },
            },
          }

  dataFrom:
    - extract:
        key: upload_assistant
    - extract:
        key: radarr
    - extract:
        key: sonarr
