---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app upload-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    ignore:
      - paths: [/spec/replicas]
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/audionut/upload-assistant
              tag: v7.1.7@sha256:9361d3c59a4fd92cf1197d0d08af635f3f7578c0c2f2b32aaea385e37115cc92
            args:
              - --webui
              - 0.0.0.0:80
            env:
              UA_BROWSE_ROOTS: /media/downloads/qbittorrent,/Upload-Assistant/tmp
              SESSION_SECRET_FILE: &session /Upload-Assistant/data/session_secret
              IN_DOCKER: 1
              PUID: 1000
              GUID: 1000
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              # capabilities: { drop: [ALL] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 80

    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.tholinka.dev'
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      media:
        type: nfs
        server: nas.servers.internal
        path: /media
        globalMounts:
          - path: /media/downloads/qbittorrent
            subPath: downloads/qbittorrent

      config:
        enabled: true
        type: secret
        externalSecretRef: files
        globalMounts:
          - path: /Upload-Assistant/data/config.py
            subPath: config.py
            readOnly: true
          - path: /Upload-Assistant/session_secret
            subPath: session-secret
            readOnly: true
          - path: *session
            subPath: session-secret
            readOnly: true
          - path: /root/.config/upload-assistant/session_secret
            subPath: session-secret
            readOnly: true
          - path: /root/.config/upload-assistant/webui_auth.json
            subPath: webui_auth.json
            readOnly: true
          - path: /Upload-Assistant/data/webui_auth.json
            subPath: webui_auth.json
            readOnly: true

      tmpfs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /Upload-Assistant/tmp
            subPath: tmp
          - path: /root/.config
            subPath: config
          - path: /Upload-Assistant/data/sessions
            subPath: sessions
          - path: /Upload-Assistant/data/banned
            subPath: sessions

    defaultExternalSecretStoreRef:
      kind: ClusterSecretStore
      name: bitwarden

    externalSecrets:
      files:
        target:
          template:
            data:
              session-secret: '{{ .UA_SESSION_SECRET }}'
              webui_auth.json: '{{ .UA_WEBUI_AUTH }}'
              config.py: |-
                config = {
                  "DEFAULT": {
                      "verbose_notification": True,
                      "tmdb_api": "{{ .TMDB_API }}",
                      "img_host_1": "onlyimage",
                      "img_host_2": "imgbox",
                      "img_host_3": "imgbb",
                      "imgbb_api": "{{ .UA_IMGBB_API }}",
                      "onlyimage_api": "{{ .UA_ONLYIMAGE_API }}",
                      "ping_unit3d": True,
                      "get_bluray_info": True,
                      "screens": "6",
                      "use_sonarr": True,
                      "sonarr_url": "http://sonarr.media.svc.cluster.local",
                      "sonarr_api_key": "{{ .SONARR_API_KEY }}",
                      "use_radarr": True,
                      "radarr_url": "http://radarr.media.svc.cluster.local",
                      "radarr_api_key": "{{ .RADARR_API_KEY }}",
                      "prefer_max_16_torrent": False,
                      "rehash_cooldown": "0",
                      "inject_delay": "0",
                      "show_upload_duration": True,
                      "print_tracker_messages": True,
                      "print_tracker_links": True,
                      "search_requests": True,
                      "check_predb": False,
                      "cross_seeding": True,
                      "cross_seed_check_everything": True,
                      "default_torrent_client": "qbittorrent",
                  },
                  "TRACKERS": {
                {{ .UA_TRACKERS | indent 4 }}
                  },
                  "TORRENT_CLIENTS": {
                      "qbittorrent": {
                          "torrent_client": "qbit",
                          "qui_proxy_url": "http://qui.media.svc.cluster.local/proxy/{{ .UA_QUI_API }}",
                          "enable_search": True,
                          "super_seed_trackers": [""],
                          "use_tracker_as_tag": False,
                          "qbit_tag": "upload-assistant",
                          "qbit_cat": "uploader",
                          "qbit_cross_tag": "cross-seed-upload-assistant",
                          "qbit_cross_cat": "cross-seed",
                          "content_layout": "Original",
                          "linking": "hardlink",
                          "allow_fallback": False,
                          "linked_folder": ["/media/downloads/qbittorrent/complete/uploader"],
                          "local_path": [""],
                          "remote_path": [""],
                      },
                  },
                }

        dataFrom:
          - extract:
              key: upload_assistant
          - extract:
              key: radarr
          - extract:
              key: sonarr
