---
# yaml-language-server: $schema=https://schemas.tholinka.dev/gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: eep
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  wasm:
    - name: eep
      rootID: eep
      code:
        type: Image
        image:
          url: oci://ghcr.io/ishioni/eep:0.2.1 # can't digest tag this, because envoy checks the digest vs module checksum not the image hash
      config:
        theme: connection
        showDetails: false
        locale: en # slim down size vs auto, otherwise get response_payload_too_large errors from envoy
        #logLevel: debug
        filterCodes: []
        excludeDomains: []
      failOpen: false
