---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8tz
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.19.0
    digest: sha256:86b90b53a8a6e6164378f291b476f67f29160577fb2c1bb5f8217cce7b6d84b2
  url: oci://ghcr.io/k8tz/k8tz/charts/k8tz
