---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8tz
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.20.0
    digest: sha256:206839f2bf0c4cdd45c1359384e3957a1304d569978d1adaf0e51ebc934c9f84
  url: oci://ghcr.io/k8tz/k8tz/charts/k8tz
