---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8tz
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.19.0
    digest: sha256:fab0f36a04ddb81392897641a8c736c3480d5e73277058498a072442798ce994
  url: oci://ghcr.io/k8tz/k8tz/charts/k8tz
