---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../metrics
patches:
  - patch: |-
      - op: replace
        path: /spec/metrics/0/external/metric
        value:
          name: ${SCALER_METRIC_NAME:=kube_statefulset_status_replicas_ready}
          selector:
            matchLabels:
              statefulset: ${SCALER_STATEFULSET}
    target:
      group: autoscaling
      kind: HorizontalPodAutoscaler
