---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      homepage:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v2.4.0@sha256:643bd0be730d40f69d58028a55d1a896739333e8815786df42bc97f109ecbe61
            env:
              HOMEPAGE_ALLOWED_HOSTS: tholinka.dev

              # Auth
              HOMEPAGE_AUTH_ENABLED: true
              HOMEPAGE_EXTERNAL_URL: https://tholinka.dev/
              HOMEPAGE_OIDC_ISSUER: https://auth.tholinka.dev/application/o/homepage/
              HOMEPAGE_OIDC_NAME: Authentik
            envFrom:
              - externalSecretRef:
                  identifier: env
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 2G
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false # does funky uid stuff
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      automountServiceAccountToken: true
      hostUsers: false

    service:
      app:
        ports:
          http:
            port: 3000

    rbac:
      roles:
        homepage:
          type: ClusterRole
          rules:
            - apiGroups:
                - ''
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - httproutes
                - gateways
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions/status
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
      bindings:
        homepage:
          type: ClusterRoleBinding
          subjects:
            - kind: ServiceAccount
              name: *app
              namespace: self-hosted # ensure matches app
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: *app

    route:
      app:
        hostnames:
          # - '{{ .Release.Name }}.tholinka.dev'
          - tholinka.dev
        parentRefs:
          # - name: envoy-internal
          #   namespace: network
          - name: envoy-internal-root
            namespace: network

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml

    defaultExternalSecretStoreRef:
      kind: ClusterSecretStore
      name: bitwarden

    externalSecrets:
      env:
        target:
          template:
            data:
              ## Auth
              HOMEPAGE_AUTH_SECRET: '{{ .HOMEPAGE_AUTH_SECRET }}'
              HOMEPAGE_OIDC_CLIENT_ID: '{{ .HOMEPAGE_CLIENT_ID }}'
              HOMEPAGE_OIDC_CLIENT_SECRET: '{{ .HOMEPAGE_CLIENT_SECRET }}'

              ## Generic
              HOMEPAGE_VAR_LATITUDE: '{{ .HASS_LATITUDE }}'
              HOMEPAGE_VAR_LONGITUDE: '{{ .HASS_LONGITUDE }}'

              ## Home
              HOMEPAGE_VAR_HA_TOKEN: '{{ .HASS_LONG_LIVED_TOKEN }}'

              ## Media
              HOMEPAGE_VAR_AUTOBRR_TOKEN: '{{ .AUTOBRR_HOMEPAGE_API_KEY }}'
              HOMEPAGE_VAR_BAZARR_TOKEN: '{{ .BAZARR_API_KEY }}'
              HOMEPAGE_VAR_LIDARR_TOKEN: '{{ .LIDARR_API_KEY }}'
              HOMEPAGE_VAR_PLEX_TOKEN: '{{ .PLEX_TOKEN }}'
              HOMEPAGE_VAR_PROWLARR_TOKEN: '{{ .PROWLARR_API_KEY }}'
              HOMEPAGE_VAR_QBITTORRENT_PROXY: 'https://qui.tholinka.dev/proxy/{{ .QBITTORRENT_PROXY }}'
              HOMEPAGE_VAR_RADARR_TOKEN: '{{ .RADARR_API_KEY }}'
              HOMEPAGE_VAR_SABNZBD_TOKEN: '{{ .SABNZBD_API_KEY }}'
              HOMEPAGE_VAR_SEERR_TOKEN: '{{ .SEERR_API_KEY }}'
              HOMEPAGE_VAR_SLSKD_TOKEN: '{{ .SLSKD_API_KEY }}'
              HOMEPAGE_VAR_SONARR_TOKEN: '{{ .SONARR_API_KEY }}'
              HOMEPAGE_VAR_TAUTULLI_TOKEN: '{{ .TAUTULLI_API_KEY }}'

              ## Security
              HOMEPAGE_VAR_AUTHENTIK_TOKEN: '{{ .AUTHENTIK_TOKEN }}'

              ## Self Hosted
              HOMEPAGE_VAR_IMMICH_TOKEN: '{{ .IMMICH_API_KEY }}'
              HOMEPAGE_VAR_PAPERLESS_TOKEN: '{{ .PAPERLESS_API_KEY }}'
        dataFrom:
          ## generic
          - extract:
              key: *app
          ## home
          - extract:
              key: home_assistant
          ## Media
          - extract:
              key: autobrr
          - extract:
              key: bazarr
          - extract:
              key: lidarr
          - extract:
              key: plex
          - extract:
              key: prowlarr
          - extract:
              key: radarr
          - extract:
              key: sabnzbd
          - extract:
              key: seerr
          - extract:
              key: slskd
          - extract:
              key: sonarr
          ## Security
          - extract:
              key: authentik
          ## Self Hosted
          - extract:
              key: immich
          - extract:
              key: paperless
