---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./replicationsource.yaml
  - ./replicationdestination.yaml
configMapGenerator:
  - name: volsync-kopia-${APP}-policy
    files:
      - global-policy.json=./config/policy.json
      - repository.config=./config/policy.json
configurations:
  - ./config/kustomizeconfig.yaml
