---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.52.0
    digest: sha256:abad7f3640346f2d44493005801b5da4dc1266ee1e540baee8faf48762b5ba8b
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
