---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shelfmark
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    ignore:
      - paths: [/spec/replicas]
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/calibrain/shelfmark
              tag: v1.2.3@sha256:bd6cb4bfa14a917e76945c22ed2c376d64cf7fdb74632435db713d42ca597b20
            env:
              FLASK_PORT: &port 80
              DEBUG: false
              BOOK_LANGUAGE: en
              CUSTOM_DNS: system

              USING_EXTERNAL_BYPASSER: true
              EXT_BYPASSER_URL: http://flaresolverr.media.svc.cluster.local:8191
              BYPASS_WARMUP_ON_CONNECT: false

              PROWLARR_ENABLED: true
              PROWLARR_URL: http://prowlarr.media.svc.cluster.local
              PROWLARR_TORRENT_CLIENT: qbittorrent
              QBITTORRENT_CATEGORY_AUDIOBOOK: audiobooks
              PROWLARR_USENET_CLIENT: sabnzbd
              SABNZBD_URL: http://sabnzbd.media.svc.cluster.local

              DISABLE_LOCAL_AUTH: true
              OIDC_AUTO_REDIRECT: true

              CALIBRE_WEB_URL: https://kavita.tholinka.dev
              BOOKS_OUTPUT_MODE: folder
              INGEST_DIR: &ingest /ingest
              FILE_ORGANIZATION: organize
              FILE_ORGANIZATION_AUDIOBOOK: organize
              TEMPLATE_ORGANIZE: '{Author}/{Title}/{Author} - {Title} ({Year})'
              TEMPLATE_AUDIOBOOK_ORGANIZE: '{Author}/{Title}/{Author} - {Title} ({Year}) {PartNumber}'
              HARDLINK_TORRENTS: true
              HARDLINK_TORRENTS_AUDIOBOOK: true

              AUTO_OPEN_DOWNLOADS_SIDEBAR: true
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /request/api/status
                    port: *port
              readiness: *probe
              startup: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits: # some of the cloudflare attempts can really spike usage
                cpu: 1
                memory: 1Gi

    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: 'OnRootMismatch'

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ['{{ .Release.Name }}.tholinka.dev']
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      downloads:
        forceRename: '{{ .Release.Name }}-downloads'
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /app/downloaded_files
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          # stupid script doesn't try creating the folder, just a file inside of it -.-
          - path: /tmp/shelfmark
            subPath: tmp-shelfmark
          - path: /home/shelfmark
            subPath: home
          - path: /var/log
            subPath: log
      media:
        type: nfs
        server: nas.servers.internal
        path: /media
        globalMounts:
          - path: *ingest
            subPath: book
