---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app booklore
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        BOOKLORE_MARIADB_PASSWORD: '{{ .BOOKLORE_MARIADB_PASSWORD }}'
        BOOKLORE_MARIADB_ROOT_PASSWORD: '{{ .BOOKLORE_MARIADB_ROOT_PASSWORD }}'
  dataFrom:
    - extract:
        key: *app
