---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app booklore
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          mariadb:
            image:
              repository: ghcr.io/mariadb/mariadb
              tag: 12.2.2-noble@sha256:beb140872ca7043376e78c03f8d6cc7edd95050d27ce13b89e1e2335053719db
            env:
              MARIADB_DATABASE: *app
              MARIADB_PASSWORD: &password
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: BOOKLORE_MARIADB_PASSWORD
              MARIADB_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: BOOKLORE_MARIADB_ROOT_PASSWORD
              MARIADB_USER: booklore
              PGID: 1000
              PUID: 1000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - bash
                      - -c
                      - |-
                        mariadb-admin ping --socket=/run/mysqld/mysqld.sock --user=root --password=$${MARIADB_ROOT_PASSWORD}
            restartPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              # NOTE: io_uring is blocked by the default containerd v2 seccomp profile
              # https://github.com/containerd/containerd/pull/9320
              seccompProfile: { type: Unconfined }

          wait-for-mariadb:
            image:
              repository: ghcr.io/wait4x/wait4x
              tag: 3.6.0@sha256:bec7ac18547781d854562c3729d3195c3880116d6758c49fdf4573ad58805f14
            args:
              - mysql
              - booklore:$(DB_PASSWORD)@tcp(localhost:3306)/booklore
            env:
              DB_PASSWORD: *password
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

        containers:
          booklore:
            image:
              repository: ghcr.io/booklore-app/booklore
              tag: v2.2.0@sha256:346064cb1fef6149dad2d8a373ea5fd1a7e3b61c22540995e40e8452136e202b
            command:
              - java
            args:
              - -jar
              - /app/app.jar
            env:
              DATABASE_PASSWORD: *password
              DATABASE_URL: jdbc:mariadb://localhost:3306/{{ .Release.Name }}
              DATABASE_USERNAME: *app
              BOOKLORE_PORT: &httpPort 80
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *httpPort
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *httpPort
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      booklore:
        ports:
          http:
            port: *httpPort

    route:
      app:
        hostnames: ['{{ .Release.Name }}.tholinka.dev']
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      data:
        existingClaim: booklore
        advancedMounts:
          booklore:
            booklore:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /var/lib/mysql
                subPath: mysql

      nfs-nas-media:
        type: nfs
        server: nas.servers.internal
        path: /media
        advancedMounts:
          booklore:
            booklore:
              - path: /book
                subPath: book
              - path: /bookdrop
                subPath: downloads/openbooks

      mysqld:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        advancedMounts:
          booklore:
            mariadb:
              - path: /run/mysqld

      tmpfs:
        type: emptyDir
        advancedMounts:
          booklore:
            booklore:
              - path: /tmp
                subPath: app
            mariadb:
              - path: /tmp
                subPath: mysql
