---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret lab-assistant-tholinka
spec:
  target:
    name: *secret
    template:
      data:
        appID: '{{ .GITHUB_APP_ID }}'
        installID: '{{ .GITHUB_APP_INSTALLATION_ID }}'
        pem: '{{ .GITHUB_APP_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: github
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret dockerhub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    template:
      data:
        DOCKERHUB_USERNAME: '{{ .DOCKERHUB_USERNAME }}'
        DOCKERHUB_TOKEN: '{{ .DOCKERHUB_TOKEN }}'
  dataFrom:
    - extract:
        key: dockerhub
