---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.0
    digest: sha256:6a49267b33a385b9610f0b7009fc1452e44d6b4be83c3a72e05befa90f5ce879
  url: oci://ghcr.io/immich-app/immich-charts/immich
