---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.1
    digest: sha256:baacb6772e8d8ea3b910e73ee5d87183359a0f67b5ee7cc1fd7bfd247d6a4380
  url: oci://ghcr.io/immich-app/immich-charts/immich
