---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  values:
    persistence:
      dragonfly-certs:
        type: custom
        globalMounts:
          - path: /var/run/secrets/dragonfly
            readOnly: true
        volumeSpec:
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: dfguard-client-ca
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/key-algorithm: ECDSA
              csi.cert-manager.io/key-size: '384'
              csi.cert-manager.io/key-encoding: PKCS8
              csi.cert-manager.io/key-usages: client auth
              csi.cert-manager.io/common-name: ${DATABASE_OWNER:=${APP}}
              csi.cert-manager.io/dns-names: ${DATABASE_OWNER:=${APP}}
