---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  values:
    persistence:
      dragonfly-certs:
        type: secret
        name: 'dragonfly-{{ .Release.Name }}-cert'
        defaultMode: 0440
        globalMounts:
          - path: /var/run/secrets/dragonfly
            readOnly: true
