---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.3
    digest: sha256:2aa792364cec7c7fe56847bc9472b92c81322fd262c74c4904e8a8beb458bf05
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
