---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.5.6
    digest: sha256:fb97019063359eec4ea8ec8be3c18ecd324358b7d247eee756fe34f45d154093
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
