---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.0
    digest: sha256:6174c62b0ff8ff55df56b6c29be0f73939f53573442ea53e50b938552fe9548a
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
