---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app bookboss
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        BOOKBOSS__ENCRYPTION_SECRET: '{{ .BOOKBOSS_ENCRYPTION_SECRET }}'
        BOOKBOSS__METADATA__HARDCOVER_API_TOKEN: '{{ .HARDCOVER_API_TOKEN }}'
        BOOKBOSS__OIDC__CLIENT_ID: '{{ .BOOKBOSS_OIDC_CLIENT_ID }}'
        BOOKBOSS__OIDC__CLIENT_SECRET: '{{ .BOOKBOSS_OIDC_CLIENT_SECRET }}'
  dataFrom:
    - extract:
        key: *app
