---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-dragonfly
stringData:
  url: rediss://dfguard.database.svc.cluster.local:6379?ssl_cert_reqs=required&ssl_certfile=/var/run/secrets/dragonfly/tls.crt&ssl_keyfile=/var/run/secrets/dragonfly/tls.key&ssl_ca_certs=/var/run/secrets/dragonfly/ca.crt
