foreground = yes
client = yes

[redis-mtls]
accept = ::1:6379
connect = dfguard.database.svc.cluster.local:6379
checkHost = dfguard.database.svc.cluster.local
cert = /var/run/secrets/dragonfly/tls.crt
key = /var/run/secrets/dragonfly/tls.key
CAfile = /var/run/secrets/dragonfly/ca.crt
verify = 2
