---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.56.0
    digest: sha256:7d08491e1a1f971f3cac69333b8ac60ea4b61a44b74b82604240443c54df4062
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
