---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatus
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.1
    digest: sha256:083f8cffd1aaaf7037afb910dece7dd238bf76b3936319ab1892eff6879b4dcf
  url: oci://ghcr.io/home-operations/charts/gatus-sidecar
