---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gatus
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.4.0
    digest: sha256:1b0a6826f8c882f5c7c63b6c13b4e28b259b7437e31b386d406379783cb59d7f
  url: oci://ghcr.io/home-operations/charts/gatus-sidecar
