---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.8
    digest: sha256:4b1785a2e63d6e4dbeb762c0880051210185c08c47cb4609fea3dbe08bb8f09a
  url: oci://ghcr.io/home-operations/charts/tuppr
