---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: blackbox-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 11.13.0
    digest: sha256:d00fa0d79c319aac9d6a3535db08afd907626fc0eb4fe68aedee65968d982739
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
