---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-s3-substitute
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: kopiur-s3-substitute
    template:
      data:
        AWS_S3_BUCKET: '{{ .AWS_S3_BUCKET }}'
        AWS_S3_ENDPOINT: '{{ .AWS_S3_ENDPOINT }}'
  dataFrom:
    - extract:
        key: kopiur_s3
