---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.5
    digest: sha256:1ac0c5be0b3695870470624a0f6fa459e4593fe792677a977be477c2e1bc4a7c
  url: oci://ghcr.io/home-operations/charts/kopiur
