---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.2
    digest: sha256:7a5012c8a5120b8b1dc52c970ee65611c783f6e3783b0acd805039c560da6775
  url: oci://ghcr.io/home-operations/charts/kopiur
