---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../metrics
patches:
  - patch: |-
      - op: replace
        path: /spec/metrics/0/external/metric
        value:
          name: probe_success
          selector:
            matchLabels:
              instance: nas.servers.internal:2049
    target:
      group: autoscaling
      kind: HorizontalPodAutoscaler
