---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-crds
spec:
  interval: 1h
  targetNamespace: database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/database/cnpg/crds
  healthChecks:
    - &crds
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusters.postgresql.cnpg.io
    - <<: *crds
      name: objectstores.barmancloud.cnpg.io
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
spec:
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/plugin-barman-cloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app postgres-cluster
spec:
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace database
  dependsOn:
    - name: cnpg-crds
      namespace: database
  postBuild:
    substitute:
      APP: cluster
    substituteFrom:
      - kind: Secret
        name: cnpg-objectstore-substitute
        optional: false
  healthChecks:
    - apiVersion: &postgresVersion postgresql.cnpg.io/v1
      kind: &postgresKind Cluster
      namespace: *namespace
      name: *app
  healthCheckExprs:
    - apiVersion: *postgresVersion
      kind: *postgresKind
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')

---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
spec:
  interval: 1h
  path: ./kubernetes/apps/database/cnpg/pgadmin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 2Gi
      KOPIUR_PUID: '5050'
      KOPIUR_PGID: '5050'
  components:
    - ../../../../components/kopiur
  dependsOn:
    - name: crds-ready
      namespace: flux-system
