---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: json-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.19.2
    digest: sha256:e1fb97f7bdb9d078b248082e9f85fc3325631f84a783d8a22e0e341f27fee864
  url: oci://ghcr.io/prometheus-community/charts/prometheus-json-exporter
