---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: json-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.20.1
    digest: sha256:c2c6d0d3338be7d1134c682e33bd36f939eeefc93ad2ce7186eff44f8e169382
  url: oci://ghcr.io/prometheus-community/charts/prometheus-json-exporter
