---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: json-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.20.0
    digest: sha256:a5c14babcab81629c58e4cf4b0a98d71d3c11bc16148e889bfffd038425a889c
  url: oci://ghcr.io/prometheus-community/charts/prometheus-json-exporter
