---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: security-ns
spec:
  provider:
    kubernetes:
      remoteNamespace: &ns security
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: *ns
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-service-account
          namespace: *ns
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/role-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-role
rules:
  - apiGroups: ['']
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-service-account
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/rolebinding-rbac-v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-eso-store-role-to-eso-service-account
subjects:
  - kind: ServiceAccount
    name: eso-service-account
roleRef:
  kind: Role
  name: eso-store-role
  apiGroup: rbac.authorization.k8s.io
