---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name whisper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    template:
      data:
        HASS_LONG_LIVED_TOKEN: '{{ .HASS_LONG_LIVED_TOKEN }}'
  dataFrom:
    - extract:
        key: home_assistant
