---
- id: github-tholinka-renovate
  execute-command: /config/renovate-operator.sh
  pass-arguments-to-command:
    - # job name
      source: string
      name: renovate-tholinka
    - # namespace
      source: string
      name: renovate
    - # body
      source: raw-request-body
  trigger-rule:
    and:
      - # Validate the webhook secret
        match:
          type: payload-hmac-sha1
          secret: >-
            {{ getenv "GITHUB_WEBHOOK_SECRET" | js }}
          parameter:
            source: header
            name: x-hub-signature
      - # Trigger only for the tholinka repo owner
        match:
          type: value
          value: tholinka
          parameter:
            source: payload
            name: repository.owner.login
