---
- id: github-tholinka-renovate
  execute-command: /config/renovate-operator.sh
  command-working-directory: /tmp
  pass-arguments-to-command:
    - # job name
      source: string
      name: renovate-tholinka
    - # namespace
      source: string
      name: renovate
    - # body
      source: raw-request-body
  pass-file-to-command:
    - # body, passing as arguments can result in `error occurred: fork/exec /config/renovate-operator.sh: argument list too long`
      source: raw-request-body
      name: payload.json
  trigger-rule:
    and:
      - # Validate the webhook secret
        match:
          type: payload-hmac-sha1
          secret: >-
            {{ getenv "GITHUB_WEBHOOK_SECRET" | js }}
          parameter:
            source: header
            name: x-hub-signature
      - # Trigger only for the tholinka repo owner
        match:
          type: value
          value: tholinka
          parameter:
            source: payload
            name: repository.owner.login
