---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              labelSelector: 'dragonfly.enable.custom/no-stunnel!=true'
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: ignored
              spec:
                template:
                  spec:
                    volumes:
                      - name: dragonfly-stunnel
                        configMap:
                          name: dragonfly-stunnel
                      - name: dragonfly-certs
                        csi:
                          driver: csi.cert-manager.io
                          readOnly: true
                          volumeAttributes:
                            csi.cert-manager.io/issuer-name: dfguard-client-ca
                            csi.cert-manager.io/issuer-kind: ClusterIssuer
                            csi.cert-manager.io/key-algorithm: ECDSA
                            csi.cert-manager.io/key-size: "384"
                            csi.cert-manager.io/key-encoding: PKCS8
                            csi.cert-manager.io/key-usages: client auth
                            csi.cert-manager.io/common-name: ${DATABASE_OWNER:=${APP}}
                            csi.cert-manager.io/dns-names: ${DATABASE_OWNER:=${APP}}


                    initContainers:
                      - name: dragonfly-stunnel
                        image: cgr.dev/chainguard/stunnel:latest@sha256:3c7424504cc0ada9578b69546061ad6de60f50a9c48a5748ceccc77332d92fb9
                        args:
                          - /etc/stunnel/stunnel.conf
                        restartPolicy: Always
                        volumeMounts:
                          - name: dragonfly-stunnel
                            mountPath: /etc/stunnel/stunnel.conf
                            subPath: stunnel.conf
                            readOnly: true
                          - name: dragonfly-certs
                            mountPath: /var/run/secrets/dragonfly
                            readOnly: true
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities:
                            drop:
                              - ALL
                          seccompProfile:
                            type: RuntimeDefault
                        resources:
                          requests:
                            cpu: 2m
                          limits:
                            memory: 32Mi

          - target:
              group: apps
              version: v1
              kind: StatefulSet
              labelSelector: 'dragonfly.enable.custom/no-stunnel!=true'
            patch: |-
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: ignored
              spec:
                template:
                  spec:
                    volumes:
                      - name: dragonfly-stunnel
                        configMap:
                          name: dragonfly-stunnel
                      - name: dragonfly-certs
                        csi:
                          driver: csi.cert-manager.io
                          readOnly: true
                          volumeAttributes:
                            csi.cert-manager.io/issuer-name: dfguard-client-ca
                            csi.cert-manager.io/issuer-kind: ClusterIssuer
                            csi.cert-manager.io/key-algorithm: ECDSA
                            csi.cert-manager.io/key-size: "384"
                            csi.cert-manager.io/key-encoding: PKCS8
                            csi.cert-manager.io/key-usages: client auth
                            csi.cert-manager.io/common-name: ${DATABASE_OWNER:=${APP}}
                            csi.cert-manager.io/dns-names: ${DATABASE_OWNER:=${APP}}

                    initContainers:
                      - name: dragonfly-stunnel
                        image: cgr.dev/chainguard/stunnel:latest@sha256:3c7424504cc0ada9578b69546061ad6de60f50a9c48a5748ceccc77332d92fb9
                        args:
                          - /etc/stunnel/stunnel.conf
                        restartPolicy: Always
                        volumeMounts:
                          - name: dragonfly-stunnel
                            mountPath: /etc/stunnel/stunnel.conf
                            subPath: stunnel.conf
                            readOnly: true
                          - name: dragonfly-certs
                            mountPath: /var/run/secrets/dragonfly
                            readOnly: true
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities:
                            drop:
                              - ALL
                          seccompProfile:
                            type: RuntimeDefault
                        resources:
                          requests:
                            cpu: 2m
                          limits:
                            memory: 32Mi
