---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              labelSelector: 'dragonfly.enable.custom/no-stunnel!=true'
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: ignored
              spec:
                template:
                  spec:
                    volumes:
                      - name: dragonfly-stunnel
                        configMap:
                          name: dragonfly-stunnel
                      - name: dragonfly-certs
                        secret:
                          secretName: dragonfly-${APP}-cert
                          defaultMode: 0440

                    initContainers:
                      - name: dragonfly-stunnel
                        image: cgr.dev/chainguard/stunnel:latest@sha256:bd75c58ee97c9139081a177509734b2aa1beaead0afe784d9d74741eb5a44451
                        args:
                          - /etc/stunnel/stunnel.conf
                        restartPolicy: Always
                        volumeMounts:
                          - name: dragonfly-stunnel
                            mountPath: /etc/stunnel/stunnel.conf
                            subPath: stunnel.conf
                            readOnly: true
                          - name: dragonfly-certs
                            mountPath: /var/run/secrets/dragonfly
                            readOnly: true
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities:
                            drop:
                              - ALL
                          seccompProfile:
                            type: RuntimeDefault
                        resources:
                          requests:
                            cpu: 2m
                          limits:
                            memory: 32Mi

          - target:
              group: apps
              version: v1
              kind: StatefulSet
              labelSelector: 'dragonfly.enable.custom/no-stunnel!=true'
            patch: |-
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: ignored
              spec:
                template:
                  spec:
                    volumes:
                      - name: dragonfly-stunnel
                        configMap:
                          name: dragonfly-stunnel
                      - name: dragonfly-certs
                        secret:
                          secretName: dragonfly-${APP}-cert
                          defaultMode: 0440

                    initContainers:
                      - name: dragonfly-stunnel
                        image: cgr.dev/chainguard/stunnel:latest@sha256:bd75c58ee97c9139081a177509734b2aa1beaead0afe784d9d74741eb5a44451
                        args:
                          - /etc/stunnel/stunnel.conf
                        restartPolicy: Always
                        volumeMounts:
                          - name: dragonfly-stunnel
                            mountPath: /etc/stunnel/stunnel.conf
                            subPath: stunnel.conf
                            readOnly: true
                          - name: dragonfly-certs
                            mountPath: /var/run/secrets/dragonfly
                            readOnly: true
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities:
                            drop:
                              - ALL
                          seccompProfile:
                            type: RuntimeDefault
                        resources:
                          requests:
                            cpu: 2m
                          limits:
                            memory: 32Mi
