---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-logs-collector
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    remoteWrite:
      - url: http://victoria-logs-server.observability.svc.cluster.local:9428
    image:
      registry: mirror.gcr.io
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
