---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ceph-csi-drivers
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.0.1
    digest: sha256:d4bc2a2bb878c9ce9ddc5b7bb4e6bac1c83e7a02f4e77cd139b8f510a7ba7b06
  url: oci://ghcr.io/home-operations/charts-mirror/ceph-csi-drivers
