---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.23.0
    digest: sha256:51da5e72f4ff654790f3226a451e798d098e5df94f7a28fedadbbc19a4af14aa
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
