---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.24.0
    digest: sha256:ad7241f410ae54765408781e3a431136247ea92e5bacf376e3f37220cac76d8d
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
