---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.27.0
    digest: sha256:a79887a5db3a121247544d8c338cca0c98f51fdc743e76ed9c5d3dfcc3feac19
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
