---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: multus
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.3.4
    digest: sha256:914f2238ee707148c94a49aa1e0c9c8ed40ac66e1cb8fc4fe66886c7df6be247
  url: oci://ghcr.io/bjw-s-labs/helm/multus
