---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kromgo
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.8
    digest: sha256:10785deefc4e6a3e94689b897a84a8ecb45319d5ac80acc8c07e5454a65f0294
  url: oci://ghcr.io/home-operations/charts/kromgo
