---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.0.0
    digest: sha256:99ef39dc5ca4642945d22c57d8503b4f57ee401404706e2381e5de2e9829fbb4
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
