---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.1.3
    digest: sha256:547459fde1ecdc4a546ed95bc10831fbdd4773b7c7533d4724193e3af7cf3718
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
