---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.5.2
    digest: sha256:57c00883e12a567c0b32750b89d29abe58d04f9c7e5d12e215e95e3f1995eb80
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
