---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonfly-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.7.0
    digest: sha256:090edee24f59cdbe4b5b4ad24f3bdf687ff83c47ad8d5099c7d6bcadafbde609
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
