---
# yaml-language-server: $schema=https://schemas.tholinka.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-gpu-resource-driver
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.1
    digest: sha256:1901047392b64f7c7913f6be61ce06a3428395e3c855476b32be02d3f89e01de
  url: oci://ghcr.io/intel/intel-gpu-resource-driver-chart
