---
# yaml-language-server: $schema=https://schemas.tholinka.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-cluster-server-cert
spec:
  secretName: *name
  dnsNames:
    - postgres-cluster-rw
    - postgres-cluster-rw.database
    - postgres-cluster-rw.database.svc
    - postgres-cluster-rw.database.svc.cluster.local
    - postgres-cluster-r
    - postgres-cluster-r.database
    - postgres-cluster-r.database.svc
    - postgres-cluster-r.database.svc.cluster.local
    - postgres-cluster-ro
    - postgres-cluster-ro.database
    - postgres-cluster-ro.database.svc
    - postgres-cluster-ro.database.svc.cluster.local
  subject:
    countries:
      - US
    organizations:
      - homelab-cluster
  usages:
    - server auth
  duration: 720h # 1 month
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always
  secretTemplate:
    labels:
      cnpg.io/reload: ''
  issuerRef:
    name: postgres-cluster-server-ca
    kind: Issuer
    group: cert-manager.io
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-cluster-client-cert
spec:
  secretName: *name
  secretTemplate:
    labels:
      cnpg.io/reload: ''
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: postgres-cluster-client-ca
    kind: ClusterIssuer
    group: cert-manager.io
