---
# yaml-language-server: $schema=https://schemas.tholinka.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres-${APP}
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: 'enabled'
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:06d950644d127249699c1468d0ffad7e44c34daa11688b0e966dec947eb043c4

  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised

  certificates:
    serverTLSSecret: postgres-cluster-server-cert
    serverCASecret: postgres-cluster-server-ca
    clientCASecret: postgres-cluster-client-ca
    replicationTLSSecret: postgres-cluster-client-cert

  storage:
    size: 5Gi
    storageClass: openebs-hostpath

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      hugepages-2Mi: 1Gi # Requires sysctl set on the host
      memory: 2Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  postgresql:
    parameters:
      max_connections: '600'
      shared_buffers: 512MB

    pg_hba:
      - hostnossl all all 10.69.0.0/16      scram-sha-256
      - hostnossl all all fc69::/16         scram-sha-256
      - hostssl   all all all               cert clientcert=verify-full

    shared_preload_libraries:
      - vchord.so
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

  monitoring:
    enablePodMonitor: false # deprecated - https://github.com/cloudnative-pg/cloudnative-pg/pull/8753

  plugins: # comment when doing for a temporary cluster for a single db restore
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: *name
        serverName: *name

  bootstrap:
    recovery:
      source: source
      # recoveryTarget:
      #   targetTime: '2026-05-22T10:00:00.000000-05:00'

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: *name
          serverName: *name

  managed:
    services:
      disabledDefaultServices: ['ro', 'r']
