---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-cnpg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: ${APP}-cnpg-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: ''
      data:
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: cloudnative_pg
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name postgres-cluster-client-ca
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: security-ns
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: ''
  data:
    - secretKey: &key ca.crt
      remoteRef:
        key: *name
        property: *key
